# Pandas

In [ ]:
import pandas as pd
# pd.__version__

### Creating a Data Frame

In [ ]:
data = {
    'Name': ['Kasra', 'Alireza', 'Masi'],
    'Age': [24, 56, None]
}

print(data)

df = pd.DataFrame(data)
df

## Reading Data

In [ ]:
csv_df = pd.read_csv("Students.csv")
csv_df

# xlsx_df = pd.read_excel("Students.xlsx")
# xlsx_df

### Data Inspection

In [5]:
df = pd.read_csv("Students.csv")

# df.head()

# df.tail()

# df.describe()

# df.info()

### Difference between Pandas Series & Numpy Arrays

In [ ]:
import numpy as np
import pandas as pd

array = np.array([10, 20, 30])
# print(array)

print(array.mean())

print("-----------------------")

series = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
# print(series)

print(series.mean())

# print(type(series[1]))
# print(type(series[0]))

# print(series['a'])
# print(series[0])

### Indexing & Selection

In [25]:
# print(df['Name'])
# print(type(df['Name']))

# a = df['GPA']
# a.mean()

# print(df[['Name', 'GPA']])

# print(df.loc[0])

print(df.iloc[0:5, 1])

0      Kasra
1     Behnam
2    Alireza
3      Erfan
4     Farbod
Name: Name, dtype: object

### Data Cleaning

In [ ]:
# new_df = df.dropna()
# new_df

# df.dropna(inplace=True)
# df

df.rename(columns={'Name': 'Full Name', 'GPD': 'GPA'}, inplace=True)
df

### Data Manipulation

In [ ]:
# data = {
#     'Class': ['A', 'B', 'A', 'B', 'A', 'B'],
#     'Students': [8, 8, 11, 12, 13, 11]
# }

# df = pd.DataFrame(data)
# df

# grouped = df.groupby('Class')

# total_students = grouped['Students'].sum()

# print(total_students)

## Filtering & Joining

### Filtering

In [ ]:
# df = pd.read_csv("Students.csv")

filterd_data = df[df['GPA'] > 15]
filterd_data

### Sorting

In [ ]:
sorted_data = df.sort_values(by='GPA')[::-1]
sorted_data

## Creating New Columns

In [6]:
# New GPA
df['NGPA'] = df['GPA'] + 1
df['Age'] = 18
df

   Unnamed: 0     Name    GPA   NGPA  Age
0           1    Kasra  18.50  19.50   18
1           2   Behnam  20.00  21.00   18
2           3  Alireza  11.70  12.70   18
3           4    Erfan    NaN    NaN   18
4           5   Farbod  16.00  17.00   18
5           6     Masi  19.00  20.00   18
6           7     Omid    NaN    NaN   18
7           8   Danial  15.78  16.78   18

## Apply Functions

In [17]:
# def add_age(x):
#     # task
#     return x + 1

df['Age'] = df['Age'].apply(lambda x: x + 1)
df

   Unnamed: 0     Name    GPA   NGPA  Age
0           1    Kasra  18.50  19.50   20
1           2   Behnam  20.00  21.00   20
2           3  Alireza  11.70  12.70   20
3           4    Erfan    NaN    NaN   20
4           5   Farbod  16.00  17.00   20
5           6     Masi  19.00  20.00   20
6           7     Omid    NaN    NaN   20
7           8   Danial  15.78  16.78   20

### Grouping

In [24]:
# df.loc[:3, 'Age'] = df.loc[:3, 'Age'].apply(lambda x: x + 1)
# df

grouped = df.groupby('Age')

gpa_mean = grouped['GPA'].mean()
gpa_mean

Age
20.0    15.780000
21.0    16.733333
Name: GPA, dtype: float64

### Handling Missing Values

In [30]:
df.fillna(value=0, inplace=True)
df

   Unnamed: 0     Name    GPA   NGPA   Age
0           1    Kasra  18.50  19.50  21.0
1           2   Behnam  20.00  21.00  21.0
2           3  Alireza  11.70  12.70  21.0
3           4    Erfan   0.00   0.00  21.0
4           5   Farbod  16.00  17.00   0.0
5           6     Masi  19.00  20.00   0.0
6           7     Omid   0.00   0.00  20.0
7           8   Danial  15.78  16.78  20.0

## Merging , Joining , Concatenating

### Merging

In [33]:
import pandas as pd

askari_df = pd.DataFrame({
    'Name': ['Ali', 'Danial', 'Rezvan', 'Moosa'],
    'GPA': [20, 19, 15, 20],
    'Class': ['A', 'B', 'C', 'D']
})

razavi_df = pd.DataFrame({
    'Absence': [2, 0, 5, 0],
    'Food': [True, False, False, False],
    'Class': ['A', 'B', 'C', 'D']
})

merged = pd.merge(askari_df, razavi_df, on='Class')
print(merged)

     Name  GPA Class  Absence   Food
0     Ali   20     A        2   True
1  Danial   19     B        0  False
2  Rezvan   15     C        5  False
3   Moosa   20     D        0  False

### Joining

In [38]:
askari_df = pd.DataFrame({
    'Name': ['Ali', 'Danial', 'Rezvan', 'Moosa'],
    'GPA': [20, 19, 15, 20],
}, index = ['A', 'B', 'C', 'D'])

razavi_df = pd.DataFrame({
    'Absence': [2, 0, 5, 0],
    'Food': [True, False, False, False],
}, index = ['A', 'B', 'C', 'D'])

joined_df = askari_df.join(razavi_df)
print(joined_df)

     Name  GPA  Absence   Food
A     Ali   20        2   True
B  Danial   19        0  False
C  Rezvan   15        5  False
D   Moosa   20        0  False

### Concatenating

#### With Same Columns

In [4]:
import pandas as pd

askari_df = pd.DataFrame({
    'Name': ['Ali', 'Danial', 'Rezvan', 'Moosa'],
    'GPA': [20, 19, 15, 20],
})

razavi_df = pd.DataFrame({
    'Name': ['Reza', 'Hadi', 'Milad', 'Sana'],
    'GPA': [12, 11, 14, 12],
})

concatenated = pd.concat([askari_df, razavi_df], axis=0, ignore_index=True)
print(concatenated)

     Name  GPA
0     Ali   20
1  Danial   19
2  Rezvan   15
3   Moosa   20
4    Reza   12
5    Hadi   11
6   Milad   14
7    Sana   12

#### With Different Columns

In [6]:
askari_df = pd.DataFrame({
    'Name': ['Ali', 'Danial', 'Rezvan', 'Moosa'],
    'GPA': [20, 19, 15, 20],
})

razavi_df = pd.DataFrame({
    'Absence': [2, 0, 5, 0],
    'Food': [True, False, False, False],
})

concatenated = pd.concat([askari_df, razavi_df], axis=1)
print(concatenated)

     Name  GPA  Absence   Food
0     Ali   20        2   True
1  Danial   19        0  False
2  Rezvan   15        5  False
3   Moosa   20        0  False